version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: vorstu_database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: Test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pg_data:/var/lib/postgresql/data

  spring_backend:
    build: ./backend
    container_name: vorstu_backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
    depends_on:
      - db

volumes:
  pg_data: